name: gameshop_deals
description: Browse through different shops and find the best deals of the games you want.
  Powered by CheapShark

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  retrofit: ^4.0.1
  in_app_review: ^2.0.6
  url_launcher: ^6.1.12
  dio: ^5.1.2
  connectivity_plus: ^4.0.1
  cached_network_image: ^3.2.3
  hooks_riverpod: ^2.3.8
  flutter_hooks: ^0.20.0
  riverpod_annotation: ^2.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  pull_to_refresh: ^2.0.0
  go_router: ^7.0.2
  flex_color_scheme: ^7.2.0
  gap: ^3.0.1
  package_info_plus: ^4.1.0
  sliver_tools: ^0.2.12

dev_dependencies:
  hive_generator: ^2.0.0
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.2
  freezed: ^2.3.4
  json_serializable: ^6.7.0
  mockito: ^5.3.2
  riverpod_generator: ^2.2.6
  ##build_resolvers: ^1.3.11
  flutter_test:
    sdk: flutter

#dependency_overrides:
# analyzer: 0.39.14
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/thumbnails/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
